# Generated by Django 5.1.6 on 2025-02-08 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetirementGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_age', models.IntegerField()),
                ('target_age', models.IntegerField()),
                ('current_savings', models.FloatField()),
                ('monthly_savings', models.FloatField()),
                ('investment_return_rate', models.FloatField()),
                ('target_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WhatIfScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_name', models.CharField(max_length=255)),
                ('estimated_amount', models.FloatField()),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulations.retirementgoal')),
            ],
        ),
    ]
