# Generated by Django 5.1.6 on 2025-02-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatifscenario',
            old_name='estimated_amount',
            new_name='future_value',
        ),
        migrations.AlterField(
            model_name='whatifscenario',
            name='scenario_name',
            field=models.CharField(max_length=100),
        ),
    ]
