# Generated by Django 5.1.6 on 2025-02-09 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0003_expense'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.RenameField(
            model_name='whatifscenario',
            old_name='scenario_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='whatifscenario',
            old_name='goal',
            new_name='retirement_goal',
        ),
        migrations.RenameField(
            model_name='whatifscenario',
            old_name='future_value',
            new_name='return_rate',
        ),
    ]
