# Generated by Django 5.1.6 on 2025-02-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0005_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('income', models.FloatField()),
                ('investment_experience', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('financial_goals', models.TextField()),
                ('risk_tolerance', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('risk_score', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
